[package]
name = "theoremify"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Marmare314"]
license = "GPL-3.0-only"
description = "A library for typesettings mathematical theorems"
repository = "https://github.com/Marmare314/theoremify"
